import Head from 'next/head'
import styles from '@/styles/Home.module.scss'


const boolean = true
const string = "Felipe"
const number = 10
const float = 10.1
const sem_resultado = undefined
const nula = null
const array = [] //listagem
const objeto = {}//envolver 1 unica coisa

const celulas = [
  {
    lider: 'Fulano',
    numero_celula: 10,
    mais_de_10: true
  },
  {
    lider: "Fulano 2",
    numero_celula: 11,
    mais_de_10: false,
    membros: ["joao", "maria", "zezinho"]
  }
]

//Exercício

//1 - Lista, 3 objetos, 7 dados, 3 strings, 2 dados boolean, 1 number, 1 objeto(2 dados, strings)

const piratas = [
  {
    name: 'Luffy',
    job: 'capitao',
    fruit: 'Gomu Gomu no Mi | Hitohito-no-mi, Model Nika',
    alive: true,
    known_pirate: true,
    reward: 3.5000000000,
    friends: ['Zoro, Sandy']
  },
  {
    name: 'Zoro',
    job: '1° commander',
    fruit: 'it does not have',
    alive: true,
    known_pirate: true,
    reward: 1.1100000000,
    friends: ['Nami, Robin']
  },
  {
    name: 'Robin',
    job: 'official',
    fruit: 'Hana Hana no Mi',
    alive: true,
    known_pirate: true,
    reward: 930.000000,
    friends: ['Chopper, Luffy']
  },
]

export default function Home() {

  return (
    <>
      <Head>
        <title>Aula-React-FPR</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}
